baseURL = 'https://XBlankZGap.github.io/resume/'
languageCode = 'en-us'
title = "Sophy's Professional Resume"
theme = 'PaperMod'

[params]
    homeInfoParams:
        Title: "Sophy | Security Researcher & Developer"
        Content: "Specializing in Infrastructure Vulnerability Assessment, SEO Auditing, and Full-Stack Development."
